import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useAuth} from "../lib/auth";
import type {ContextTypes} from "../lib/auth";

const Home: NextPage = () => {
  const auth: ContextTypes = useAuth();

  return (
    <div className={styles.container}>
      <Head>
        <title>Fast Feedback</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fast Feedback
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <button onClick={() => auth.signInWithGitHub()}>Sign In With Github</button>
        <div>
          {auth?.user?.email}
        </div>
        {auth.user && (
          <button onClick={() => auth.sign_out()}>Sign Out</button>
        )}
      </main>
    </div>
  )
}

export default Home;
