import type {NextPage} from 'next'
import Head from 'next/head'
import {useAuth} from "@/lib/auth";
import type {ContextTypes} from "@/lib/auth";
import { Button, Heading, Code } from "@chakra-ui/react";

const Home: NextPage = () => {
  const auth: ContextTypes = useAuth();

  return (
    <div>
      <Head>
        <title>Fast Feedback</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Heading>
          Fast Feedback
        </Heading>

        <p>
          Get started by editing{' '}
          <Code>pages/index.tsx</Code>
        </p>

        <Button onClick={() => auth.signInWithGitHub()}>Sign In With Github</Button>
        <div>
          {auth?.user?.email}
        </div>
        {auth.user && (
          <Button onClick={() => auth.sign_out()}>Sign Out</Button>
        )}
      </main>
    </div>
  )
}

export default Home;
